version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Root project
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm

  - package-ecosystem: "npm"
    directory: "/forge-sql-orm-cli"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm

  - package-ecosystem: "npm"
    directory: "/examples/forge-sql-orm-example-drizzle-driver-simple"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm

  - package-ecosystem: "npm"
    directory: "/examples/forge-sql-orm-example-drizzle-driver-simple/static/forge-orm-example"
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "@types/react"
      - dependency-name: "@types/react-dom"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm

  - package-ecosystem: "npm"
    directory: "/examples/forge-sql-orm-example-simple"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm

  - package-ecosystem: "npm"
    directory: "/examples/forge-sql-orm-example-simple/static/forge-orm-example"
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "@types/react"
      - dependency-name: "@types/react-dom"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm

  - package-ecosystem: "npm"
    directory: "/examples/forge-sql-orm-example-optimistic-locking"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm

  - package-ecosystem: "npm"
    directory: "/examples/forge-sql-orm-example-optimistic-locking/static/forge-orm-example"
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "@types/react"
      - dependency-name: "@types/react-dom"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm

  - package-ecosystem: "npm"
    directory: "/examples/forge-sql-orm-example-dynamic"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm

  - package-ecosystem: "npm"
    directory: "/examples/forge-sql-orm-example-dynamic/static/forge-orm-example"
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "@types/react"
      - dependency-name: "@types/react-dom"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm
