/**
 * This file was auto-generated by forge-sql-orm
 * Generated at: 2025-05-15T09:51:36.737Z
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Any changes will be overwritten on next generation
 */

export * from "./schema";

export interface VersionFieldMetadata {
  fieldName: string;
}

export interface TableMetadata {
  tableName: string;
  versionField: VersionFieldMetadata;
}

export type AdditionalMetadata = Record<string, TableMetadata>;

export const additionalMetadata: AdditionalMetadata = {
  issue_check_list: {
    tableName: "issue_check_list",
    versionField: {
      fieldName: "updatedAt",
    },
  },
};
