/**
 * This file was auto-generated by forge-sql-orm
 * Generated at: 2025-03-24T20:06:43.321Z
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Any changes will be overwritten on next generation
 */

export * from "./relations";
export * from "./schema";

export interface VersionFieldMetadata {
  fieldName: string;
}

export interface TableMetadata {
  tableName: string;
  versionField: VersionFieldMetadata;
}

export type AdditionalMetadata = Record<string, TableMetadata>;

export const additionalMetadata: AdditionalMetadata = {
  test_data_optimistic_date: {
    tableName: "test_data_optimistic_date",
    versionField: {
      fieldName: "version",
    },
  },
  test_data_optimistic_number: {
    tableName: "test_data_optimistic_number",
    versionField: {
      fieldName: "version",
    },
  },
  test_data_optimistic_timestamp: {
    tableName: "test_data_optimistic_timestamp",
    versionField: {
      fieldName: "version",
    },
  },
};
